spring:
   devtools:
      restart:
         enabled: true
   h2:
      console:
         enabled: true
         path: /h2/console
meep:
   wsrest:
      resources:
         url: https://apidev.meep.me/tripplan/api/v1/routers/lisboa/resources
         params:
            lowerLeftLatLon: 38.711046,-9.160096
            upperRightLatLon: 38.739429,-9.137115
            companyZoneIds: 545,467,473